### ISSUE TITLE
Broken link in "Recommended CHERI Reading list from the point of the CapableVMs team"

### ISSUE THREAD

**Issue by tel3path** [capablevms/docs#2]
Broken link in [Recommended CHERI Reading list from the point of the CapableVMs team](https://github.com/capablevms/docs/blob/master/reading-list.md): Link to ISA specification for [Morello](https://documentation-service.arm.com/static/5f8da6fef86e16515cdb861e) gets a 404 error.

**Comment by ltratt** [comment]
Alex isn't part of the project any more so I've unassigned him. Since this looks like a nice simple fix, this looks like an excellent PR opportunity for you @tel3path :) Please give our PR process docs at https://ykjit.github.io/ykdocs/contributing/prs.html a read, and then give the PR a shot!
